[package]
name = "xpallet-gateway-common-rpc-runtime-api"
version = "2.0.1"
authors = ["The ChainX Authors"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false }

# Substrate primitives
sp-api = { version = "2.0.0", default-features = false }
sp-runtime = { version = "2.0.0", default-features = false }
sp-std = { version = "2.0.0", default-features = false }

# ChainX primitives
chainx-primitives = { path = "../../../../../primitives", default-features = false }
xp-runtime = { path = "../../../../../primitives/runtime", default-features = false }

# ChainX pallets
xpallet-assets = { path = "../../../../assets", default-features = false }
xpallet-gateway-common = { path = "../../", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    # Substrate primitives
    "sp-api/std",
    "sp-runtime/std",
    "sp-std/std",
    # ChainX primitives
    "chainx-primitives/std",
    "xp-runtime/std",
    # ChainX pallets
    "xpallet-assets/std",
    "xpallet-gateway-common/std",
]
