[package]
name = "xrml-session"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io> & Chainpool <chainx.org>"]

[dependencies]
hex-literal = "0.1.0"
serde = { version = "1.0", default-features = false }
safe-mix = { version = "1.0", default-features = false}
substrate-primitives = { git = "https://github.com/chainpool/substrate", default-features = false }
parity-codec = { version = "3.0", default-features = false }
parity-codec-derive = { version = "3.0", default-features = false }
sr-std = { git = "https://github.com/chainpool/substrate", default-features = false }
sr-io = { git = "https://github.com/chainpool/substrate", default-features = false }
sr-primitives = { git = "https://github.com/chainpool/substrate", default-features = false }
srml-support = { git = "https://github.com/chainpool/substrate", default-features = false }
srml-consensus = { git = "https://github.com/chainpool/substrate", default-features = false }
srml-system = { git = "https://github.com/chainpool/substrate", default-features = false }
srml-timestamp = { git = "https://github.com/chainpool/substrate", default-features = false }

# chainx runtime module
xrml-xsystem = { path = "../xsystem", default-features = false }
xrml-xaccounts = { path = "../xaccounts", default-features = false }

[features]
default = ["std"]
std = [
	"serde/std",
	"safe-mix/std",
	"parity-codec/std",
	"parity-codec-derive/std",
	"substrate-primitives/std",
	"sr-std/std",
	"sr-io/std",
	"srml-support/std",
	"sr-primitives/std",
	"srml-consensus/std",
	"srml-system/std",
	"srml-timestamp/std",
	# xrml
	"xrml-xsystem/std",
	"xrml-xaccounts/std",
]
