[package]
name = "xpallet-gateway-common"
version = "2.0.0-alpha.4"
authors = ["The ChainX Authors"]
edition = "2018"

[dependencies]
bs58 = { version = "0.3", default-features = false, features = ["alloc"] }
codec = { package = "parity-scale-codec", version = "1.3.4", features = ["derive"], default-features = false }
hex = { version = "0.4", optional = true }
serde = { version = "1.0", optional = true }

# Substrate primitives
sp-core = { version = "2.0.0", default-features = false, optional = true }
sp-runtime = { version = "2.0.0", default-features = false }
sp-std = { version = "2.0.0", default-features = false }

# Substrate pallets
frame-benchmarking = { version = "2.0.0", default-features = false, optional = true }
frame-support = { version = "2.0.0", default-features = false }
frame-system = { version = "2.0.0", default-features = false }

# ChainX primitives
chainx-primitives = { path = "../../../primitives", default-features = false }
xp-logging =  { path = "../../../primitives/logging", default-features = false }
xp-io = { path = "../../../primitives/io", default-features = false, optional = true }
xp-protocol = { path = "../../../primitives/protocol", default-features = false }
xp-runtime = { path = "../../../primitives/runtime", default-features = false }

# ChainX pallets
xpallet-assets = { path = "../../assets", default-features = false }
xpallet-assets-registrar = { path = "../../assets-registrar", default-features = false }
xpallet-gateway-records = { path = "../records", default-features = false }
xpallet-support = { path = "../../support", default-features = false }

# light-bitcoin
light-bitcoin = { git = "https://github.com/chainx-org/light-bitcoin", branch = "master", default-features = false }

[dev-dependencies]
hex = "0.4"
lazy_static = "1.4"
sp-io = "2.0.0"
pallet-balances = "2.0.0"
xpallet-gateway-bitcoin = { path = "../bitcoin" }

[features]
default = ["std"]
std = [
    "bs58/std",
    "codec/std",
    "hex",
    "serde",
    # Substrate primitives
    "sp-core/std",
    "sp-runtime/std",
    "sp-std/std",
    # Substrate pallets
    "frame-support/std",
    "frame-system/std",
    # ChainX primitives
    "chainx-primitives/std",
    "xp-logging/std",
    "xp-io/std",
    "xp-protocol/std",
    "xp-runtime/std",
    # ChainX pallets
    "xpallet-assets/std",
    "xpallet-assets-registrar/std",
    "xpallet-gateway-records/std",
    "xpallet-support/std",
    # light-bitcoin
    "light-bitcoin/std",
]
runtime-benchmarks = [
    "sp-core",
    "frame-benchmarking",
]
ss58check = [
    "xp-io"
]
