[package]
name = "xpallet-gateway-common"
version = "2.0.9"
authors = ["The ChainX Authors"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", features = ["derive"], default-features = false }
hex = { version = "0.4", default-features = false, optional = true }
serde = { version = "1.0", optional = true }

# Substrate primitives
sp-core = { version = "3.0.0", default-features = false, optional = true }
sp-runtime = { version = "3.0.0", default-features = false }
sp-std = { version = "3.0.0", default-features = false }

# Substrate pallets
frame-benchmarking = { version = "3.0.0", default-features = false, optional = true }
frame-support = { version = "3.0.0", default-features = false }
frame-system = { version = "3.0.0", default-features = false }

# ChainX primitives
chainx-primitives = { path = "../../../primitives", default-features = false }
xp-protocol = { path = "../../../primitives/protocol", default-features = false }
xp-rpc = { path = "../../../primitives/rpc", optional = true }
xp-runtime = { path = "../../../primitives/runtime", default-features = false }

# ChainX pallets
xpallet-assets = { path = "../../assets", default-features = false }
xpallet-assets-registrar = { path = "../../assets-registrar", default-features = false }
xpallet-gateway-records = { path = "../records", default-features = false }
xpallet-support = { path = "../../support", default-features = false }

# light-bitcoin
light-bitcoin = { git = "https://github.com/chainx-org/light-bitcoin", branch = "btc-like", default-features = false }

[dev-dependencies]
lazy_static = "1.4"
serde_json = "1.0"
sp-io = "3.0.0"
frame-benchmarking = "3.0.0"
pallet-balances = "3.0.0"
xp-gateway-bitcoin = { path = "../../../primitives/gateway/bitcoin" }
xpallet-gateway-bitcoin = { path = "../bitcoin/v1" }

[features]
default = ["std"]
std = [
    "codec/std",
    "hex/std",
    "serde",
    # Substrate primitives
    "sp-core/std",
    "sp-runtime/std",
    "sp-std/std",
    # Substrate pallets
    "frame-support/std",
    "frame-system/std",
    # ChainX primitives
    "chainx-primitives/std",
    "xp-protocol/std",
    "xp-rpc",
    "xp-runtime/std",
    # ChainX pallets
    "xpallet-assets/std",
    "xpallet-assets-registrar/std",
    "xpallet-gateway-records/std",
    "xpallet-support/std",
    # light-bitcoin
    "light-bitcoin/std",
]
runtime-benchmarks = ["hex", "sp-core", "frame-benchmarking"]
