[package]
name = "xpallet-gateway-common"
version = "3.0.0"
authors = ["The ChainX Authors"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.3.1", features = ["derive"], default-features = false }
hex = { version = "0.4", default-features = false, optional = true }
serde = { version = "1.0", optional = true }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }

# Substrate primitives
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11", default-features = false, optional = true }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11", default-features = false }

# Substrate pallets
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11", default-features = false, optional = true }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11", default-features = false }

pallet-elections-phragmen = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11", default-features = false }

# ChainX primitives
chainx-primitives = { path = "../../../primitives", default-features = false }
# xp-logging = { path = "../../../primitives/logging", default-features = false }
xp-protocol = { path = "../../../primitives/protocol", default-features = false }
xp-rpc = { path = "../../../primitives/rpc", optional = true }
xp-runtime = { path = "../../../primitives/runtime", default-features = false }

# ChainX pallets
xpallet-assets = { path = "../../assets", default-features = false }
xpallet-assets-registrar = { path = "../../assets-registrar", default-features = false }
xpallet-gateway-records = { path = "../records", default-features = false }
xpallet-support = { path = "../../support", default-features = false }

# light-bitcoin
light-bitcoin = { git = "https://github.com/chainx-org/light-bitcoin", branch = "taproot", default-features = false }
musig2 = { git = "https://github.com/chainx-org/Musig2", branch = "lib", default-features = false }

[dev-dependencies]
lazy_static = "1.4"
serde_json = "1.0"
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }
xp-gateway-bitcoin = { path = "../../../primitives/gateway/bitcoin" }
xpallet-gateway-bitcoin = { path = "../bitcoin" }

[features]
default = ["std"]
std = [
  "codec/std",
  "hex/std",
  "serde",
  "scale-info/std",
  # Substrate primitives
  "sp-core/std",
  "sp-runtime/std",
  "sp-std/std",
  # Substrate pallets
  "frame-support/std",
  "frame-system/std",
  # ChainX primitives
  "chainx-primitives/std",
  "xp-protocol/std",
  "xp-rpc",
  "xp-runtime/std",
  # ChainX pallets
  "xpallet-assets/std",
  "xpallet-assets-registrar/std",
  "xpallet-gateway-records/std",
  "xpallet-support/std",
  # light-bitcoin
  "light-bitcoin/std",
  "pallet-elections-phragmen/std"
]
runtime-benchmarks = ["hex", "sp-core", "frame-benchmarking"]
