[package]
name = "xpallet-gateway-common"
version = "2.0.0-alpha.0"
authors = ["The ChainX Authors"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", features = ["derive"], default-features = false }
bs58 = { version = "0.3", default-features = false, features = ["alloc"] }
hex = { version = "0.4", optional = true }
serde = { version = "1.0", optional = true }

sp-std = { version = "2.0.0", default-features = false }
sp-runtime = { version = "2.0.0", default-features = false }
sp-core = { version = "2.0.0", default-features = false, optional = true }

frame-support = { version = "2.0.0", default-features = false }
frame-system = { version = "2.0.0", default-features = false }

frame-benchmarking = { version = "2.0.0", default-features = false, optional = true }

# chainx runtime module
chainx-primitives = { path = "../../../primitives", default-features = false }
xp-runtime = { path = "../../../primitives/runtime", default-features = false }
xp-io = { path = "../../../primitives/io", default-features = false, optional = true }

xpallet-protocol = { path = "../../protocol", default-features = false }
xpallet-support = { path = "../../support", default-features = false }
xpallet-assets = { path = "../../assets", default-features = false }
xpallet-assets-registrar = { path = "../../assets-registrar", default-features = false }
xpallet-gateway-records = { path = "../records", default-features = false }

# light-bitcoin
light-bitcoin = { git = "https://github.com/chainx-org/light-bitcoin", branch = "master", default-features = false }

[dev-dependencies]
hex = "0.4"
lazy_static = "1.4"

sp-io = { version = "2.0.0" }

pallet-balances = { version = "2.0.0" }
xpallet-gateway-bitcoin = { path = "../bitcoin" }

[features]
default = ["std"]
std = [
    "codec/std",
    "hex",
    "serde",
    "bs58/std",

    "sp-std/std",
    "sp-runtime/std",
    "sp-core/std",

    "frame-support/std",
    "frame-system/std",

    # chainx runtime module
    "chainx-primitives/std",
    "xp-io/std",
    "xp-runtime/std",

    "xpallet-protocol/std",
    "xpallet-support/std",
    "xpallet-assets/std",
    "xpallet-assets-registrar/std",
    "xpallet-gateway-records/std",

    # light-bitcoin
    "light-bitcoin/std",
]
ss58check = [
    "xp-io"
]
runtime-benchmarks = [
    "frame-benchmarking",
    "sp-core"
]
