[package]
name = "xpallet-gateway-common-rpc"
version = "2.0.0-alpha.0"
authors = ["The ChainX Authors"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4" }
hex = "0.4"
jsonrpc-core = { version = "15.0.0", features = ["arbitrary_precision"] }
jsonrpc-core-client = { version = "15.0.0", features = ["arbitrary_precision"] }
jsonrpc-derive = "15.0.0"

sp-api = "2.0.0"
sp-runtime = "2.0.0"
sp-blockchain = "2.0.0"

xpallet-gateway-common-rpc-runtime-api = { path = "./runtime-api" }
