[package]
name = "chainx-primitives"
version = "0.3.0"
authors = ["Chainpool <http://www.chainx.org>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
primitives = { package = "substrate-primitives", git = "https://github.com/chainpool/substrate", default-features = false }
rstd = { package = "sr-std", git = "https://github.com/chainpool/substrate", default-features = false }
runtime-primitives = { package = "sr-primitives", git = "https://github.com/chainpool/substrate", default-features = false }

[features]
default = ["std"]
std = [
    "serde/std",
    "serde_derive",
    "primitives/std",
    "rstd/std",
    "runtime-primitives/std",
]
