[package]
name = "chainx-primitives"
version = "2.0.0"
authors = ["ChainX community <http://www.chainx.org>"]
edition = "2018"

[dependencies]
sp-std = { git = "https://github.com/paritytech/substrate.git", tag = "v2.0.0-rc3", default-features = false }

[features]
default = ["std"]
std = [
    "sp-std/std",
]