stages:
  - test

test-linux:
  stage: test
  image: paritytech/ci-linux:production
  script:
    - rustup show
    - cargo --version
    - sccache -s
    - time cargo test --workspace --locked --release --verbose
