[package]
name = "xpallet-contracts"
version = "2.0.0-rc4"
authors = ["Parity Technologies <admin@parity.io> and ChainX community <https://www.chainx.org>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/chainx-org/ChainX"
description = "ChainX pallet for WASM contracts"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
pwasm-utils = { version = "0.12.0", default-features = false }
codec = { package = "parity-scale-codec", version = "1.3.1", default-features = false, features = ["derive"] }
parity-wasm = { version = "0.41.0", default-features = false }
wasmi-validation = { version = "0.3.0", default-features = false }

# Substrate primitives
sp-core = { version = "2.0.0-rc5", default-features = false }
sp-runtime = { version = "2.0.0-rc5", default-features = false }
sp-io = { version = "2.0.0-rc5", default-features = false }
sp-std = { version = "2.0.0-rc5", default-features = false }
sp-sandbox = { version = "0.8.0-rc5", default-features = false }

# Substrate pallets
frame-support = { version = "2.0.0-rc5", default-features = false }
frame-system = { version = "2.0.0-rc5", default-features = false }

# ChainX primitives
chainx-primitives = { path = "../../primitives", default-features = false }
xpallet-contracts-primitives = { path = "./common", default-features = false }

# ChainX pallets
xpallet-support = { path = "../support", default-features = false }
xpallet-assets = { path = "../assets", default-features = false }

[dev-dependencies]
wabt = "0.9.2"
assert_matches = "1.3.0"
hex-literal = "0.2.1"
pallet-balances = { version = "2.0.0-rc5" }
pallet-timestamp = { version = "2.0.0-rc5" }
pallet-randomness-collective-flip = { version = "2.0.0-rc5" }

[features]
default = ["std"]
std = [
    "serde",
    "codec/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-io/std",
    "sp-std/std",
    "sp-sandbox/std",
    "frame-support/std",
    "frame-system/std",
    "parity-wasm/std",
    "pwasm-utils/std",
    "wasmi-validation/std",

    "chainx-primitives/std",
    "xpallet-support/std",
    "xpallet-assets/std",
    "xpallet-contracts-primitives/std",
]
