[package]
name = "xpallet-gateway-bitcoin-rpc"
version = "5.1.1"
authors = ["The ChainX Authors"]
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" }
serde = { version = "1.0.101", features = ["derive"] }
hex = "0.4"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = "18.0.0"
jsonrpc-derive = "18.0.0"

# Substrate primitives
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }

# ChainX primitives
xp-rpc = { path = "../../../../primitives/rpc" }

# ChainX pallets api
xpallet-gateway-bitcoin-rpc-runtime-api = { path = "./runtime-api" }
