[package]
name = "xpallet-gateway-bitcoin"
version = "2.0.0-alpha.0"
authors = ["The ChainX Authors"]
edition = "2018"

[dependencies]
bs58 = { version = "0.3", default-features = false, features = ["alloc"] }
codec = { package = "parity-scale-codec", version = "1.3.4", features = ["derive"], default-features = false }
serde = { version = "1.0", optional = true }

# Substrate primitives
sp-core = { version = "2.0.0", default-features = false }
sp-runtime = { version = "2.0.0", default-features = false }
sp-std = { version = "2.0.0", default-features = false }
sp-io = { version = "2.0.0", default-features = false }
# Substrate pallets
frame-support = { version = "2.0.0", default-features = false }
frame-system = { version = "2.0.0", default-features = false }

frame-benchmarking = { version = "2.0.0", default-features = false, optional = true }

pallet-timestamp = { version = "2.0.0", default-features = false }

# orml
orml-utilities = { version = "0.2.1-dev", git = "https://github.com/open-web3-stack/open-runtime-module-library.git", rev = "b023edf1d9bbd9062c8adf27ebff1737d434f127", default-features = false }

# ChainX primitives
chainx-primitives = { path = "../../../primitives", default-features = false }
xp-io = { path = "../../../primitives/io", default-features = false }

# ChainX pallets
xpallet-assets = { path = "../../assets", default-features = false }
xpallet-protocol = { path = "../../protocol", default-features = false }
xpallet-support = { path = "../../support", default-features = false }
xpallet-gateway-common = { path = "../common", default-features = false }
xpallet-gateway-records = { path = "../records", default-features = false }

# light-bitcoin
light-bitcoin = { git = "https://github.com/chainx-org/light-bitcoin", branch = "v2", default-features = false }

[dev-dependencies]
lazy_static = "1.4"
hex = "0.4"
serde_json = "1.0"
pallet-balances = { version = "2.0.0" }
pallet-multisig = { version = "2.0.0" }

xpallet-assets-registrar = { path = "../../assets-registrar" }

[features]
default = ["std"]
std = [
    "bs58/std",
    "codec/std",
    "serde",

    "sp-core/std",
    "sp-runtime/std",
    "sp-std/std",
    "sp-io/std",

    "frame-support/std",
    "frame-system/std",
    "frame-benchmarking/std",
    "pallet-timestamp/std",

    "orml-utilities/std",

    "chainx-primitives/std",
    "xp-io/std",

    "xpallet-assets/std",
    "xpallet-protocol/std",
    "xpallet-support/std",
    "xpallet-gateway-common/std",
    "xpallet-gateway-records/std",

    # light-bitcoin
    "light-bitcoin/std",
]
runtime-benchmarks = [
    "frame-benchmarking",
]
