[package]
name = "xpallet-gateway-bitcoin"
version = "3.0.0"
authors = ["The ChainX Authors"]
edition = "2018"

[dependencies]
bs58 = { version = "0.3", default-features = false, features = ["alloc"] }
codec = { package = "parity-scale-codec", version = "2.3.1", features = ["derive"], default-features = false }
hex = { version = "0.4", default-features = false }
serde = { version = "1.0", optional = true }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }

# Substrate primitives
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11", default-features = false }

# Substrate pallets
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11", default-features = false, optional = true }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11", default-features = false }

pallet-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11", default-features = false }
xpallet-assets = { path = "../../assets", default-features = false }

# Orml
orml-utilities = { git = "https://github.com/chainx-org/ormls", branch = "main", default-features = false }

# ChainX primitives
chainx-primitives = { path = "../../../primitives", default-features = false }
xp-assets-registrar = { path = "../../../primitives/assets-registrar", default-features = false }
xp-gateway-bitcoin = { path = "../../../primitives/gateway/bitcoin", default-features = false }
xp-gateway-common = { path = "../../../primitives/gateway/common", default-features = false }
xp-protocol = { path = "../../../primitives/protocol", default-features = false }

# ChainX pallets
xpallet-gateway-common = { path = "../common", default-features = false }
xpallet-gateway-records = { path = "../records", default-features = false }
xpallet-support = { path = "../../support", default-features = false }

# light-bitcoin
light-bitcoin = { git = "https://github.com/chainx-org/light-bitcoin", branch = "taproot", default-features = false }
musig2 = { git = "https://github.com/chainx-org/Musig2", branch = "lib", default-features = false }

[dev-dependencies]
hex = "0.4"
hex-literal = "0.3"
lazy_static = "1.4"
serde_json = "1.0"
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }
pallet-multisig = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }
pallet-elections-phragmen = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }
xp-assets-registrar = { path = "../../../primitives/assets-registrar" }

[features]
default = ["std"]
std = [
    "bs58/std",
    "codec/std",
    "hex/std",
    "serde",
    "scale-info/std",
    # Substrate primitives
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-std/std",
    # Substrate pallets
    "frame-support/std",
    "frame-system/std",
    "pallet-timestamp/std",
    # Orml
    "orml-utilities/std",
    # ChainX primitives
    "chainx-primitives/std",
    "xp-assets-registrar/std",
    "xp-gateway-bitcoin/std",
    "xp-gateway-common/std",
    "xp-protocol/std",
    # ChainX pallets
    "xpallet-gateway-common/std",
    "xpallet-gateway-records/std",
    "xpallet-support/std",
    # light-bitcoin
    "light-bitcoin/std",
    "musig2/std",
]
runtime-benchmarks = ["frame-benchmarking"]
ss58check = ["xp-gateway-common/ss58check"]
