[package]
name = "xpallet-gateway-bitcoin"
version = "5.1.0"
authors = ["The ChainX Authors"]
edition = "2021"

[dependencies]
bs58 = { version = "0.3", default-features = false, features = ["alloc"] }
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"], default-features = false }
hex = { version = "0.4", default-features = false }
serde = { version = "1.0", optional = true }
scale-info = { version = "2.0.1", default-features = false, features = ["derive"] }

# Substrate primitives
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18", default-features = false }

# Substrate pallets
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18", default-features = false, optional = true }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18", default-features = false }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18", default-features = false }
pallet-evm = { git = "https://github.com/chainx-org/frontier", branch = "polkadot-v0.9.18-btc", default-features = false, features = ["chainx-adaptor"] }

# Asset bridge
xpallet-assets-bridge = { path = "../../assets-bridge", default-features = false }


# ChainX primitives
chainx-primitives = { path = "../../../primitives", default-features = false }
xp-gateway-bitcoin = { path = "../../../primitives/gateway/bitcoin", default-features = false }
xp-gateway-common = { path = "../../../primitives/gateway/common", default-features = false }
xp-protocol = { path = "../../../primitives/protocol", default-features = false }

# ChainX pallets
xpallet-assets = { path = "../../assets", default-features = false }
xpallet-gateway-common = { path = "../common", default-features = false }
xpallet-gateway-records = { path = "../records", default-features = false }
xpallet-support = { path = "../../support", default-features = false }

# light-bitcoin
light-bitcoin = { git = "https://github.com/chainx-org/light-bitcoin", branch = "develop-2022", default-features = false }

[dev-dependencies]
hex = "0.4"
hex-literal = "0.3"
lazy_static = "1.4"
serde_json = "1.0"
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
pallet-multisig = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
pallet-elections-phragmen = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
xp-assets-registrar = { path = "../../../primitives/assets-registrar" }
xpallet-assets-registrar = { path = "../../assets-registrar" }


[features]
default = ["std"]
std = [
    "bs58/std",
    "codec/std",
    "hex/std",
    "serde",
    "scale-info/std",
    # Substrate primitives
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-std/std",
    # Substrate pallets
    "frame-support/std",
    "frame-system/std",
    "pallet-timestamp/std",
    "pallet-evm/std",
    # Asset bridge
    "xpallet-assets-bridge/std",
    # ChainX primitives
    "chainx-primitives/std",
    "xp-gateway-bitcoin/std",
    "xp-gateway-common/std",
    "xp-protocol/std",
    # ChainX pallets
    "xpallet-assets/std",
    "xpallet-gateway-common/std",
    "xpallet-gateway-records/std",
    "xpallet-support/std",
    # light-bitcoin
    "light-bitcoin/std",
]
runtime-benchmarks = ["frame-benchmarking"]
ss58check = ["xp-gateway-common/ss58check"]
try-runtime = ["frame-support/try-runtime"]
