[package]
name = "xpallet-genesis-builder"
version = "2.0.0-beta.2"
authors = ["The ChainX Authors"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
serde = { version = "1.0", optional = true }

# Substrate primitives
sp-core = { version = "2.0.0", default-features = false }
sp-runtime = { version = "2.0.0", default-features = false }
sp-std = { version = "2.0.0", default-features = false }

# Substrate pallets
frame-support = { version = "2.0.0", default-features = false }
frame-system = { version = "2.0.0", default-features = false }
pallet-balances = { version = "2.0.0", default-features = false }

# ChainX primitives
chainx-primitives = { path = "../../primitives", default-features = false }
xp-genesis-builder = { path = "../../primitives/genesis-builder", default-features = false }
xp-logging = { path = "../../primitives/logging", default-features = false }
xp-protocol = { path = "../../primitives/protocol", default-features = false }

# ChainX pallets
xpallet-assets = { path = "../assets", default-features = false }
xpallet-mining-asset = { path  = "../mining/asset", default-features = false }
xpallet-mining-staking = { path  = "../mining/staking", default-features = false }
xpallet-support = { path = "../support", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "serde",
    # Substrate primitives
    "sp-core/std",
    "sp-runtime/std",
    "sp-std/std",
    # Substrate pallets
    "frame-support/std",
    "frame-system/std",
    "pallet-balances/std",
    # ChainX primitives
    "chainx-primitives/std",
    "xp-genesis-builder/std",
    "xp-logging/std",
    "xp-protocol/std",
    # ChainX pallets
    "xpallet-assets/std",
    "xpallet-mining-asset/std",
    "xpallet-mining-staking/std",
    "xpallet-support/std",
]
