[package]
name = "xpallet-genesis-builder"
version = "4.1.1"
authors = ["The ChainX Authors"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.3.1", default-features = false, features = ["derive"] }
serde = { version = "1.0", optional = true }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }

# Substrate primitives
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11", default-features = false }

# Substrate pallets
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11", default-features = false }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11", default-features = false }

# ChainX primitives
chainx-primitives = { path = "../../primitives", default-features = false }
xp-genesis-builder = { path = "../../primitives/genesis-builder", default-features = false }
xp-protocol = { path = "../../primitives/protocol", default-features = false }

# ChainX pallets
xpallet-assets = { path = "../assets", default-features = false }
xpallet-mining-asset = { path  = "../mining/asset", default-features = false }
xpallet-mining-staking = { path  = "../mining/staking", default-features = false }
xpallet-support = { path = "../support", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "serde",
    "scale-info/std",
    # Substrate primitives
    "sp-runtime/std",
    "sp-std/std",
    # Substrate pallets
    "frame-support/std",
    "frame-system/std",
    "pallet-balances/std",
    # ChainX primitives
    "chainx-primitives/std",
    "xp-genesis-builder/std",
    "xp-protocol/std",
    # ChainX pallets
    "xpallet-assets/std",
    "xpallet-mining-asset/std",
    "xpallet-mining-staking/std",
    "xpallet-support/std",
]
