[package]
name = "xrml-fee-manager"
version = "0.4.0"
authors = ["Chainpol <http://www.chainx.org>"]

[dependencies]
serde = { version = "1.0", default-features = false }
parity-codec = { version = "2.1", default-features = false }
sr-std = { git = "https://github.com/chainpool/substrate", default-features = false }
sr-primitives = { git = "https://github.com/chainpool/substrate", default-features = false }
srml-system = { git = "https://github.com/chainpool/substrate", default-features = false }
srml-balances = { git = "https://github.com/chainpool/substrate", default-features = false }
srml-support = { git = "https://github.com/chainpool/substrate", default-features = false }

# xrml
xrml-xsystem = { path = "../../xsystem", default-features = false }

[features]
default = ["std"]
std = [
    "serde/std",
    "parity-codec/std",
    "sr-std/std",
    "sr-primitives/std",
    "srml-system/std",
    "srml-balances/std",
    "srml-support/std",

    # xrml
    "xrml-xsystem/std",
]
