[package]
name = "xpallet-transaction-fee-rpc"
version = "2.0.4"
authors = ["The ChainX Authors"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.1" }
jsonrpc-core = "15.0.0"
jsonrpc-core-client = "15.0.0"
jsonrpc-derive = "15.0.0"
serde = { version = "1.0.101", features = ["derive"] }

# Substrate primitives
sp-api = "2.0.0"
sp-blockchain = "2.0.0"
sp-core = "2.0.0"
sp-runtime = "2.0.0"

# Substrate pallets
pallet-transaction-payment-rpc = "2.0.0"

xp-rpc = { path = "../../../primitives/rpc" }

# ChainX pallets api
xpallet-transaction-fee-rpc-runtime-api = { path = "./runtime-api" }
