[package]
name = "xpallet-mining-staking"
version = "0.1.0"
authors = ["ChainX community <https://www.chainx.org>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.1", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true }

# Substrate primitives
sp-std = { git = "https://github.com/paritytech/substrate.git", tag = "v2.0.0-rc4", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate.git", tag = "v2.0.0-rc4", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", tag = "v2.0.0-rc4", default-features = false }
sp-arithmetic = { git = "https://github.com/paritytech/substrate.git", tag = "v2.0.0-rc4", default-features = false }

# Substrate pallets
frame-support = { git = "https://github.com/paritytech/substrate.git", tag = "v2.0.0-rc4", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate.git", tag = "v2.0.0-rc4", default-features = false }
pallet-session = { git = "https://github.com/paritytech/substrate.git", tag = "v2.0.0-rc4", default-features = false }

# ChainX primitives
chainx-primitives = { path = "../../../primitives", default-features = false }
xp-mining-common = { path  = "../../../primitives/mining/common", default-features = false }
xp-mining-staking = { path  = "../../../primitives/mining/staking", default-features = false }

# ChainX pallets
xpallet-assets = { path = "../../assets", default-features = false }
xpallet-support = { path = "../../support", default-features = false }

[dev-dependencies]
xpallet-protocol = { path = "../../protocol" }
sp-core = { git = "https://github.com/paritytech/substrate.git", tag = "v2.0.0-rc4" }
sp-io = { git = "https://github.com/paritytech/substrate.git", tag = "v2.0.0-rc4" }
env_logger = "0.7.1"

[features]
default = ["std"]
std = [
    "codec/std",
    "serde",

    "sp-std/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-arithmetic/std",

    "frame-support/std",
    "frame-system/std",
    "pallet-session/std",

    "chainx-primitives/std",
    "xp-mining-common/std",
    "xp-mining-staking/std",

    "xpallet-assets/std",
    "xpallet-support/std",
]
