[package]
name = "xpallet-assets-rpc-runtime-api"
version = "5.2.1"
authors = ["The ChainX Authors"]
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }

# Substrate primitives
sp-api = { git = "https://github.com/chainx-org/substrate", branch = "polkadot-v0.9.18", default-features = false }
sp-std = { git = "https://github.com/chainx-org/substrate", branch = "polkadot-v0.9.18", default-features = false }

# ChainX primitives
chainx-primitives = { path = "../../../../primitives", default-features = false }

# ChainX pallets
xpallet-assets = { path = "../../", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    # Substrate primitives
    "sp-api/std",
    "sp-std/std",
    # ChainX primitives
    "chainx-primitives/std",
    # ChainX pallets
    "xpallet-assets/std",
]
