[package]
name = "xpallet-assets-rpc-runtime-api"
version = "2.0.0-alpha.0"
authors = ["The ChainX Authors"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
sp-api = { version = "2.0.0-rc6", default-features = false }
sp-std = { version = "2.0.0-rc6", default-features = false }

chainx-primitives = { path = "../../../../primitives", default-features = false }

xpallet-assets = { path = "../../", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "sp-api/std",
    "sp-std/std",

    "chainx-primitives/std",

    "xpallet-assets/std",
]
