[package]
name = "chainx-service"
version = "2.0.8-1"
authors = ["The ChainX Authors"]
edition = "2018"

[dependencies]
futures = "0.3.4"

# Substrate client
sc-authority-discovery = "0.9.0"
sc-basic-authorship = "0.9.0"
sc-chain-spec = "3.0.0"
sc-client-api = "3.0.0"
sc-consensus = "0.9.0"
sc-consensus-babe = "0.9.0"
sc-consensus-slots = "0.9.0"
sc-executor = "0.9.0"
sc-finality-grandpa = "0.9.0"
sc-finality-grandpa-warp-sync = "0.9.0"
sc-network = "0.9.0"
sc-rpc = "3.0.0"
sc-transaction-pool = "3.0.0"
sc-telemetry = "3.0.0"
sc-service = "0.9.0"

sp-api = "3.0.0"
sp-authority-discovery = "3.0.0"
sp-blockchain = "3.0.0"
sp-block-builder = "3.0.0"
sp-core = "3.0.0"
sp-consensus = "0.9.0"
sp-consensus-babe = "0.9.0"
sp-finality-grandpa = "3.0.0"
sp-inherents = "3.0.0"
sp-runtime = "3.0.0"
sp-transaction-pool = "3.0.0"
sp-offchain = "3.0.0"
sp-session = "3.0.0"

frame-system-rpc-runtime-api = "3.0.0"
pallet-transaction-payment-rpc-runtime-api = "3.0.0"

chainx-executor = { path = "../executor" }
chainx-primitives = { path = "../primitives" }
chainx-rpc = { path = "../rpc" }
chainx-runtime = { path = "../runtime/chainx" }
dev-runtime = { path = "../runtime/dev" }
malan-runtime = { path = "../runtime/malan" }

xpallet-assets-rpc-runtime-api = { path = "../xpallets/assets/rpc/runtime-api" }
xpallet-dex-spot-rpc-runtime-api = { path = "../xpallets/dex/spot/rpc/runtime-api" }
xpallet-gateway-common-rpc-runtime-api = { path = "../xpallets/gateway/common/rpc/runtime-api" }
xpallet-gateway-bitcoin-v2-rpc-runtime-api = { path = "../xpallets/gateway/bitcoin/v2/rpc/runtime-api" }
xpallet-gateway-records-rpc-runtime-api = { path = "../xpallets/gateway/records/rpc/runtime-api" }
xpallet-mining-asset-rpc-runtime-api = { path = "../xpallets/mining/asset/rpc/runtime-api" }
xpallet-mining-staking-rpc-runtime-api = { path = "../xpallets/mining/staking/rpc/runtime-api" }
xpallet-transaction-fee-rpc-runtime-api = { path = "../xpallets/transaction-fee/rpc/runtime-api" }
