[package]
name = "xpallet-contracts-rpc"
version = "0.8.0-rc4"
authors = ["Parity Technologies <admin@parity.io> and ChainX community <https://www.chainx.org>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "Node-specific RPC methods for interaction with contracts."

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.1" }
serde = { version = "1.0.101", features = ["derive"] }
hex = "0.4"

jsonrpc-core = "14.2.0"
jsonrpc-core-client = "14.2.0"
jsonrpc-derive = "14.2.1"

sp-blockchain = { version = "2.0.0-rc5" }
sp-core = { version = "2.0.0-rc5" }
sp-rpc = { version = "2.0.0-rc5" }
sp-runtime = { version = "2.0.0-rc5" }
sp-api = { version = "2.0.0-rc5" }

chainx-primitives = { path = "../../../primitives" }
xpallet-contracts-primitives = { path = "../common" }
xpallet-contracts-rpc-runtime-api = { path = "./runtime-api" }

[dev-dependencies]
serde_json = "1.0.41"
