[package]
name = "xrml-xmining-staking"
version = "1.0.0"
authors = ["Chainpool <http://chainx.org>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "3.3", default-features = false, features = ["derive"] }
# Substrate
rstd = { package = "sr-std", git = "https://github.com/chainpool/substrate", default-features = false }
primitives = { package = "sr-primitives", git = "https://github.com/chainpool/substrate", default-features = false }
support = { package = "srml-support", git = "https://github.com/chainpool/substrate", default-features = false }
system = { package = "srml-system", git = "https://github.com/chainpool/substrate", default-features = false }
consensus = { package = "srml-consensus", git = "https://github.com/chainpool/substrate", default-features = false }
# ChainX
xr-primitives = { path = "../../../xr-primitives", default-features = false }
xsystem = { package = "xrml-xsystem", path = "../../xsystem", default-features = false }
xaccounts = { package = "xrml-xaccounts", path = "../../xaccounts", default-features = false }
xsupport = { package = "xrml-xsupport", path = "../../xsupport", default-features = false }
xassets = { package = "xrml-xassets-assets", path = "../../xassets/assets", default-features = false }
xsession = { package = "xrml-xsession", path = "../../xsession", default-features = false }
xbridge-features = { package = "xrml-xbridge-features", path = "../../xbridge/features", default-features = false }

[dev-dependencies]
# Substrate
substrate-primitives = { git = "https://github.com/chainpool/substrate" }
runtime-io = { package = "sr-io", git = "https://github.com/chainpool/substrate" }
indices = { package = "srml-indices", git = "https://github.com/chainpool/substrate" }
timestamp = { package ="srml-timestamp", git = "https://github.com/chainpool/substrate" }
# ChainX
xfee-manager = { package = "xrml-xfee-manager", path = "../../xfee/manager" }
xrecords = { package = "xrml-xassets-records", path = "../../xassets/records" }
xbitcoin = { package = "xrml-xbridge-bitcoin", path = "../../xbridge/bitcoin" }
xbridge-features = { package = "xrml-xbridge-features", path = "../../xbridge/features" }
xbridge-common = { package = "xrml-xbridge-common", path = "../../xbridge/common" }
xmultisig = { package = "xrml-xmultisig", path = "../../xmultisig", default-features = false }

[features]
default = ["std"]
std = [
    "serde/std",
    "serde_derive",
    "parity-codec/std",
    # Substrate
    "rstd/std",
    "primitives/std",
    "support/std",
    "system/std",
    "consensus/std",
    # ChainX
    "xr-primitives/std",
    "xsystem/std",
    "xaccounts/std",
    "xsupport/std",
    "xassets/std",
    "xsession/std",
    "xbridge-features/std",
]
