[package]
name = "xrml-xassets-assets"
version = "0.4.0"
authors = ["Chainpool <https://www.chainx.org>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "3.3", default-features = false, features = ["derive"] }
# Substrate
rstd = { package = "sr-std", git = "https://github.com/chainpool/substrate", default-features = false }
runtime-io = { package = "sr-io", git = "https://github.com/chainpool/substrate", default-features = false }
primitives = { package = "sr-primitives", git = "https://github.com/chainpool/substrate", default-features = false }
support = { package = "srml-support", git = "https://github.com/chainpool/substrate", default-features = false }
system = { package = "srml-system", git = "https://github.com/chainpool/substrate", default-features = false }
# ChainX
xr-primitives = { path = "../../../xr-primitives", default-features = false }
xsupport = { package = "xrml-xsupport", path = "../../xsupport", default-features = false }

[dev-dependencies]
# Substrate
substrate-primitives = { git = "https://github.com/chainpool/substrate" }
indices = { package = "srml-indices", git = "https://github.com/chainpool/substrate" }

[features]
default = ["std"]
std = [
    "serde/std",
    "serde_derive",
    "parity-codec/std",
    # Substrate
    "rstd/std",
    "runtime-io/std",
    "primitives/std",
    "support/std",
    "system/std",
    # ChainX
    "xr-primitives/std",
    "xsupport/std",
]
