[package]
name = "xrml-grandpa"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io> & Chainpool<chainx.org>"]

[dependencies]
hex-literal = "0.1.0"
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "3.0", default-features = false }
parity-codec-derive = { version = "3.0", default-features = false }
substrate-primitives = { git = "https://github.com/chainpool/substrate", default-features = false }
substrate-finality-grandpa-primitives = { git = "https://github.com/chainpool/substrate", default-features = false }
sr-std = { git = "https://github.com/chainpool/substrate", default-features = false }
sr-io = { git = "https://github.com/chainpool/substrate", default-features = false }
sr-primitives = { git = "https://github.com/chainpool/substrate", default-features = false }
srml-support = { git = "https://github.com/chainpool/substrate", default-features = false }
srml-system = { git = "https://github.com/chainpool/substrate", default-features = false }
srml-consensus = { git = "https://github.com/chainpool/substrate", default-features = false }
xrml-session = { path = "../xsession", default-features = false }

[features]
default = ["std"]
std = [
	"serde/std",
	"serde_derive",
	"parity-codec/std",
	"substrate-primitives/std",
	"substrate-finality-grandpa-primitives/std",
	"sr-std/std",
	"sr-io/std",
	"srml-support/std",
	"sr-primitives/std",
	"srml-system/std",
    "srml-consensus/std",
	"xrml-session/std",
]
