[package]
name = "xpallet-gateway-records-rpc-runtime-api"
version = "3.0.0"
authors = ["The ChainX Authors"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.3.1", default-features = false, features = ["derive"] }

# Substrate primitives
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11", default-features = false }

# ChainX primitives
sherpax-primitives = { path = "../../../../../primitives", default-features = false }
xp-assets-registrar = { path = "../../../../../primitives/assets-registrar", default-features = false }

# ChainX pallets
xpallet-gateway-records = { path = "../../", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    # Substrate primitives
    "sp-api/std",
    "sp-std/std",
    # ChainX primitives
    "sherpax-primitives/std",
    "xp-assets-registrar/std",
    # ChainX pallets
    "xpallet-gateway-records/std",
]
