[package]
name = "xrml-xsupport"
version = "0.4.0"
authors = ["Chainpool <https://www.chainx.org>"]
edition = "2018"

[dependencies]
log = { version = "0.4", optional = true }
serde = { version = "1.0", default_features = false }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "3.0", default-features = false }
parity-codec-derive = { version = "3.0", default-features = false }

sr-std = { git = "https://github.com/chainpool/substrate", default_features = false }
sr-io = { git = "https://github.com/chainpool/substrate", default_features = false }
sr-primitives = { git = "https://github.com/chainpool/substrate", default_features = false }
srml-support = { git = "https://github.com/chainpool/substrate", default_features = false }

[features]
default = ["std"]
std = [
    "log",
    "serde/std",
    "serde_derive",
    "parity-codec/std",
    "parity-codec-derive/std",
    "sr-std/std",
    "sr-io/std",
    "sr-primitives/std",
    "srml-support/std",
]
