[package]
name = "xrml-xsupport"
version = "0.4.0"
authors = ["Chainpool <https://www.chainx.org>"]
edition = "2018"

[dependencies]
log = { version = "0.4", optional = true }
rustc-hex = { version = "2.0", optional = true }
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "3.2", default-features = false, features = ["derive"] }
# Substrate
rstd = { package = "sr-std", git = "https://github.com/chainpool/substrate", default-features = false }
primitives = { package = "sr-primitives", git = "https://github.com/chainpool/substrate", default-features = false }
support = { package = "srml-support", git = "https://github.com/chainpool/substrate", default-features = false }

[features]
default = ["std"]
std = [
    "log",
    "rustc-hex",
    "serde/std",
    "serde_derive",
    "parity-codec/std",
    # Substrate
    "rstd/std",
    "primitives/std",
    "support/std",
]
