[package]
name = "xrml-xassets-process"
version = "0.4.0"
authors = ["Chainpool <http://chainx.org>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "3.3", default-features = false, features = ["derive"] }
# Substrate
rstd = { package = "sr-std", git = "https://github.com/chainpool/substrate", default-features = false }
runtime-io = { package = "sr-io", git = "https://github.com/chainpool/substrate", default-features = false }
primitives = { package = "sr-primitives", git = "https://github.com/chainpool/substrate", default-features = false }
support = { package = "srml-support", git = "https://github.com/chainpool/substrate", default-features = false }
system = { package = "srml-system", git = "https://github.com/chainpool/substrate", default-features = false }
# ChainX
xsupport = { package = "xrml-xsupport", path = "../../xsupport", default-features = false }
xassets = { package = "xrml-xassets-assets", path = "../assets", default-features = false }
xrecords = { package = "xrml-xassets-records", path = "../records", default-features = false }
xbitcoin = { package = "xrml-xbridge-bitcoin", path = "../../xbridge/bitcoin", default-features = false }

[dev-dependencies]
# Substrate
substrate-primitives = { git = "https://github.com/chainpool/substrate" }
timestamp = { package = "srml-timestamp", git = "https://github.com/chainpool/substrate" }
consensus = { package = "srml-consensus", git = "https://github.com/chainpool/substrate" }
# ChainX
xsystem = { package = "xrml-xsystem", path = "../../xsystem" }
xaccounts = { package = "xrml-xaccounts", path = "../../xaccounts" }
xfee_manager = { package = "xrml-xfee-manager", path = "../../xfee/manager" }

[features]
default = ["std"]
std = [
    "serde/std",
    "serde_derive",
    "parity-codec/std",
    # Substrate
    "rstd/std",
    "runtime-io/std",
    "primitives/std",
    "support/std",
    "system/std",
    # ChainX
    "xsupport/std",
    "xassets/std",
    "xrecords/std",
    "xbitcoin/std",
]
