[package]
name = "xpallet-dex-spot-rpc-runtime-api"
version = "2.0.9"
authors = ["The ChainX Authors"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }

# Substrate primitives
sp-api = { version = "3.0.0", default-features = false }
sp-std = { version = "3.0.0", default-features = false }

# ChainX pallets
xpallet-dex-spot = { path = "../..", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    # Substrate primitives
    "sp-api/std",
    "sp-std/std",
    # ChainX pallets
    "xpallet-dex-spot/std",
]
