[package]
name = "xp-protocol"
version = "2.0.5"
authors = ["The ChainX Authors"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", features = ["derive"], default-features = false }
serde = { version = "1.0", features = ["derive"], optional = true }

# Substrate primitives
sp-runtime = { version = "2.0.0", default-features = false }

# ChainX primitives
chainx-primitives = { path = "..", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "serde",
    # Substrate primitives
    "sp-runtime/std",
    # ChainX primitives
    "chainx-primitives/std",
]
