[package]
name = "xpallet-dex-spot-rpc"
version = "0.1.0"
authors = ["ChainX community <https://www.chainx.org>"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.1" }
serde = { version = "1.0.10", features = ["derive"] }
sp-api = { git = "https://github.com/paritytech/substrate.git", tag = "v2.0.0-rc4" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", tag = "v2.0.0-rc4" }
sp-std = { git = "https://github.com/paritytech/substrate.git", tag = "v2.0.0-rc4" }
sp-blockchain = { git = "https://github.com/paritytech/substrate.git", tag = "v2.0.0-rc4" }
jsonrpc-core = "14.2.0"
jsonrpc-derive = "14.2.1"
jsonrpc-core-client = "14.2.0"
xpallet-dex-spot = { path = "../" }
xpallet-dex-spot-rpc-runtime-api = { path = "./runtime-api" }
xpallet-support = { path = "../../../support" }
