[package]
name = "xp-rpc"
version = "2.0.0-pre.2"
authors = ["The ChainX Authors"]
edition = "2018"

[dependencies]
hex = "0.4"
jsonrpc-core = "15.0.0"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0"
