[package]
name = "xp-rpc"
version = "5.2.0"
authors = ["The ChainX Authors"]
edition = "2021"

[dependencies]
hex = "0.4"
jsonrpc-core = "18.0.0"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0"
