[package]
name = "xr-primitives"
version = "0.4.0"
authors = ["Chainpool <http://www.chainx.org>"]

[dependencies]
num-traits = { version = "0.2", default-features = false }
integer-sqrt = { version = "0.1.2" }
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "2.1", default-features = false }
parity-codec-derive = { version = "2.1", default-features = false }
substrate-primitives = { git = "https://github.com/chainpool/substrate", default_features = false }
sr-std = { git = "https://github.com/chainpool/substrate/", default_features = false }
sr-io = { git = "https://github.com/chainpool/substrate/", default_features = false }
sr-primitives = { git = "https://github.com/chainpool/substrate/", default_features = false }

[dev-dependencies]
serde_json = "1.0"

[features]
default = ["std"]
std = [
    "num-traits/std",
    "serde",
    "serde_derive",
    "sr-std/std",
    "sr-io/std",
    "sr-primitives/std",
    "parity-codec/std",
    "substrate-primitives/std",
]
api-for-runtime = []
