[package]
name = "xpallet-gateway-records-rpc"
version = "2.0.0-alpha.3"
authors = ["The ChainX Authors"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4" }
serde = { version = "1.0.101", features = ["derive"] }
jsonrpc-core = "15.0.0"
jsonrpc-core-client = "15.0.0"
jsonrpc-derive = "15.0.0"

# Substrate primitives
sp-api = "2.0.0"
sp-blockchain = "2.0.0"
sp-runtime = "2.0.0"

# ChainX primitives
xp-rpc = { path = "../../../../primitives/rpc" }

# ChainX pallets
xpallet-support = { path = "../../../support" }

# ChainX pallets api
xpallet-gateway-records-rpc-runtime-api = { path = "./runtime-api" }
