[package]
name = "xrml-xaura"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io> & Chainpool <chainx.org>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "3.2", default-features = false, features = ["derive"] }
# Substrate
inherents = { package = "substrate-inherents", git = "https://github.com/chainpool/substrate", default-features = false }
rstd = { package = "sr-std", git = "https://github.com/chainpool/substrate", default-features = false }
primitives = { package = "sr-primitives",git = "https://github.com/chainpool/substrate", default-features = false }
support = { package = "srml-support", git = "https://github.com/chainpool/substrate", default-features = false }
timestamp = { package = "srml-timestamp", git = "https://github.com/chainpool/substrate", default-features = false }
# ChainX
xstaking = { package = "xrml-xmining-staking", path = "../xmining/staking", default-features = false }

[dev-dependencies]
lazy_static = "1.0"
parking_lot = "0.7.1"
substrate-primitives = { git = "https://github.com/chainpool/substrate" }
runtime-io = { package = "sr-io", git = "https://github.com/chainpool/substrate" }
system = { package = "srml-system", git = "https://github.com/chainpool/substrate" }
consensus = { package = "srml-consensus", git = "https://github.com/chainpool/substrate" }

[features]
default = ["std"]
std = [
	"serde/std",
	"serde_derive",
	"parity-codec/std",
	# Substrate
	"inherents/std",
	"rstd/std",
	"primitives/std",
	"support/std",
	"timestamp/std",
	# ChainX
	"xstaking/std",
]
