[package]
name = "xp-mining-staking"
version = "2.0.0-alpha"
authors = ["ChainX community <https://www.chainx.org>"]
edition = "2018"

[dependencies]
# Substrate primitives
sp-std = { version = "2.0.0-rc6", default-features = false }
sp-runtime = { version = "2.0.0-rc6", default-features = false }

# ChainX primitives
chainx-primitives = { path = "../../../primitives", default-features = false }
xp-mining-common = { path = "../common", default-features = false }

[features]
default = ["std"]
std = [
    "sp-std/std",
    "sp-runtime/std",

    "chainx-primitives/std",
    "xp-mining-common/std",
]
