[package]
name = "xp-mining-staking"
version = "2.0.6"
authors = ["The ChainX Authors"]
edition = "2018"

[dependencies]
# Substrate primitives
sp-runtime = { version = "2.0.0", default-features = false }
sp-std = { version = "2.0.0", default-features = false }

# ChainX primitives
chainx-primitives = { path = "../../../primitives", default-features = false }
xp-mining-common = { path = "../common", default-features = false }

[features]
default = ["std"]
std = [
    # Substrate primitives
    "sp-runtime/std",
    "sp-std/std",
    # ChainX primitives
    "chainx-primitives/std",
    "xp-mining-common/std",
]
