[package]
name = "xpallet-mining-staking-rpc"
version = "2.0.7"
authors = ["The ChainX Authors"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4" }
jsonrpc-core = "15.0.0"
jsonrpc-core-client = "15.0.0"
jsonrpc-derive = "15.0.0"

# Substrate primitives
sp-api = "2.0.0"
sp-blockchain = "2.0.0"
sp-runtime = "2.0.0"

# ChainX primitives
xp-rpc = { path = "../../../../primitives/rpc" }

# ChainX pallets api
xpallet-mining-staking-rpc-runtime-api = { path = "./runtime-api" }
