[package]
name = "xpallet-mining-staking-rpc"
version = "2.0.0-alpha.0"
authors = ["The ChainX Authors"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4" }
serde = { version = "1.0.101", features = ["derive"] }
jsonrpc-core = { version = "14.2.0", features = ["arbitrary_precision"] }
jsonrpc-core-client = { version = "14.2.0", features = ["arbitrary_precision"] }
jsonrpc-derive = "14.2.2"

sp-api = "2.0.0-rc6"
sp-runtime = "2.0.0-rc6"
sp-blockchain = "2.0.0-rc6"

xpallet-mining-staking-rpc-runtime-api = { path = "./runtime-api" }
