[package]
name = "xrml-xsystem"
version = "0.4.0"
authors = ["Chainpool <http://chainx.org>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "3.3", default-features = false, features = ["derive"] }
# Substrate
inherents = { package = "substrate-inherents", git = "https://github.com/chainpool/substrate", default-features = false }
rstd = { package = "sr-std", git = "https://github.com/chainpool/substrate", default-features = false }
support = { package = "srml-support", git = "https://github.com/chainpool/substrate", default-features = false }
system = { package = "srml-system", git = "https://github.com/chainpool/substrate", default-features = false }
# ChainX
xsupport = { package = "xrml-xsupport", path = "../xsupport", default-features = false }

[features]
default = ["std"]
std = [
    "serde/std",
    "serde_derive",
    "parity-codec/std",
    # Substrate
    "inherents/std",
    "rstd/std",
    "support/std",
    "system/std",
    # ChainX
    "xsupport/std",
]
