[package]
name = "xpallet-mining-asset"
version = "2.0.0-alpha.2"
authors = ["The ChainX Authors"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true }

# Substrate primitives
sp-arithmetic = { version = "2.0.0", default-features = false }
sp-core = { version = "2.0.0", default-features = false }
sp-runtime = { version = "2.0.0", default-features = false }
sp-std = { version = "2.0.0", default-features = false }

# Substrate pallets
frame-benchmarking = { version = "2.0.0", default-features = false, optional = true }
frame-support = { version = "2.0.0", default-features = false }
frame-system = { version = "2.0.0", default-features = false }

# ChainX primitives
chainx-primitives = { path = "../../../primitives", default-features = false }
xp-mining-common = { path  = "../../../primitives/mining/common", default-features = false }
xp-mining-staking = { path  = "../../../primitives/mining/staking", default-features = false }
xp-protocol = { path = "../../../primitives/protocol", default-features = false }

# ChainX pallets
xpallet-assets = { path = "../../assets", default-features = false }
xpallet-assets-registrar = { path = "../../assets-registrar", default-features = false }
xpallet-mining-staking = { path = "../../mining/staking", default-features = false }
xpallet-support = { path = "../../support", default-features = false }

[dev-dependencies]
env_logger = "0.7.1"
sp-core = "2.0.0"
sp-io = "2.0.0"
frame-benchmarking = "2.0.0"
pallet-balances = "2.0.0"
pallet-session = "2.0.0"
pallet-timestamp = "2.0.0"

[features]
default = ["std"]
std = [
    "codec/std",
    "serde",
    # Substate primitives
    "sp-arithmetic/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-std/std",
    # Substrte pallets
    "frame-support/std",
    "frame-system/std",
    # ChainX primitives
    "chainx-primitives/std",
    "xp-mining-common/std",
    "xp-mining-staking/std",
    "xp-protocol/std",
    # ChainX pallets
    "xpallet-assets/std",
    "xpallet-assets-registrar/std",
    "xpallet-mining-staking/std",
    "xpallet-support/std",
]
runtime-benchmarks = [
    "frame-benchmarking",
]
