[package]
name = "xpallet-mining-asset"
version = "3.0.0"
authors = ["The ChainX Authors"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.3.1", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }

# Substrate primitives
sp-arithmetic = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11", default-features = false }

# Substrate pallets
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11", default-features = false, optional = true }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11", default-features = false }

# ChainX primitives
chainx-primitives = { path = "../../../primitives", default-features = false }
xp-mining-common = { path  = "../../../primitives/mining/common", default-features = false }
xp-mining-staking = { path  = "../../../primitives/mining/staking", default-features = false }
xp-protocol = { path = "../../../primitives/protocol", default-features = false }

# ChainX pallets
xpallet-assets = { path = "../../assets", default-features = false }
xpallet-assets-registrar = { path = "../../assets-registrar", default-features = false }
xpallet-mining-staking = { path = "../../mining/staking", default-features = false }
xpallet-support = { path = "../../support", default-features = false }

[dev-dependencies]
env_logger = "0.7.1"
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }
pallet-session = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }

[features]
default = ["std"]
std = [
    "codec/std",
    "serde",
    "scale-info/std",
    # Substate primitives
    "sp-arithmetic/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-std/std",
    # Substrte pallets
    "frame-support/std",
    "frame-system/std",
    # ChainX primitives
    "chainx-primitives/std",
    "xp-mining-common/std",
    "xp-mining-staking/std",
    "xp-protocol/std",
    # ChainX pallets
    "xpallet-assets/std",
    "xpallet-assets-registrar/std",
    "xpallet-mining-staking/std",
    "xpallet-support/std",
]
runtime-benchmarks = [
    "frame-benchmarking",
]
