[package]
name = "xpallet-mining-asset"
version = "2.0.0-alpha.0"
authors = ["The ChainX Authors"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true }

# Substrate primitives
sp-std = { version = "2.0.0-rc6", default-features = false }
sp-core = { version = "2.0.0-rc6", default-features = false }
sp-runtime = { version = "2.0.0-rc6", default-features = false }
sp-arithmetic = { version = "2.0.0-rc6", default-features = false }

# Substrate pallets
frame-support = { version = "2.0.0-rc6", default-features = false }
frame-system = { version = "2.0.0-rc6", default-features = false }

frame-benchmarking = { version = "2.0.0-rc6", default-features = false, optional = true }

# ChainX primitives
chainx-primitives = { path = "../../../primitives", default-features = false }
xp-mining-common = { path  = "../../../primitives/mining/common", default-features = false }
xp-mining-staking = { path  = "../../../primitives/mining/staking", default-features = false }

# ChainX pallets
xpallet-assets-registrar = { path = "../../assets-registrar", default-features = false }
xpallet-assets = { path = "../../assets", default-features = false }
xpallet-protocol = { path = "../../protocol", default-features = false }
xpallet-support = { path = "../../support", default-features = false }
xpallet-mining-staking = { path = "../../mining/staking", default-features = false }

[dev-dependencies]
sp-core = { version = "2.0.0-rc6" }
sp-io = { version = "2.0.0-rc6" }
pallet-session = { version = "2.0.0-rc6" }
pallet-timestamp = { version = "2.0.0-rc6" }
pallet-balances = { version = "2.0.0-rc6" }
frame-benchmarking = { version = "2.0.0-rc6" }
env_logger = "0.7.1"

[features]
default = ["std"]
std = [
    "codec/std",
    "serde",

    "sp-std/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-arithmetic/std",

    "frame-support/std",
    "frame-system/std",

    "chainx-primitives/std",
    "xp-mining-common/std",
    "xp-mining-staking/std",

    "xpallet-assets-registrar/std",
    "xpallet-assets/std",
    "xpallet-protocol/std",
    "xpallet-support/std",
    "xpallet-mining-staking/std",
]
runtime-benchmarks = [
    "frame-benchmarking",
]
