[package]
name = "xpallet-assets-rpc"
version = "2.0.9"
authors = ["The ChainX Authors"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0" }
jsonrpc-core = "15.1.0"
jsonrpc-core-client = "15.1.0"
jsonrpc-derive = "15.1.0"

# Substrate primitives
sp-api = "3.0.0"
sp-blockchain = "3.0.0"
sp-runtime = "3.0.0"

# ChainX primitives
xp-rpc = { path = "../../../primitives/rpc" }

# ChainX pallets api
xpallet-assets-rpc-runtime-api = { path = "./runtime-api" }
