[package]
name = "xpallet-assets-rpc"
version = "2.0.0-alpha.0"
authors = ["The ChainX Authors"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4" }
serde = { version = "1.0.101", features = ["derive"] }
jsonrpc-core = "14.2.0"
jsonrpc-core-client = "14.2.0"
jsonrpc-derive = "14.2.1"

sp-api = { version = "2.0.0-rc6" }
sp-runtime = { version = "2.0.0-rc6" }
sp-blockchain = { version = "2.0.0-rc6" }

chainx-primitives = { path = "../../../primitives" }
xpallet-support = { path = "../../support" }
xpallet-assets-rpc-runtime-api = { path = "./runtime-api" }
