[package]
name = "xpallet-assets-rpc"
version = "0.1.0"
authors = ["ChainX community <https://www.chainx.org>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.1" }
serde = { version = "1.0.101", features = ["derive"] }
jsonrpc-core = "14.2.0"
jsonrpc-core-client = "14.2.0"
jsonrpc-derive = "14.2.1"

sp-api = { version = "2.0.0-rc5" }
sp-runtime = { version = "2.0.0-rc5" }
sp-blockchain = { version = "2.0.0-rc5" }

chainx-primitives = { path = "../../../primitives" }
xpallet-assets-rpc-runtime-api = { path = "./runtime-api" }
