[package]
name = "xp-assets-registrar"
version = "2.0.0-alpha.0"
authors = ["The ChainX Authors"]
edition = "2018"

[dependencies]
impl-trait-for-tuples = "0.1.3"

frame-support = { version = "2.0.0", default-features = false }

chainx-primitives = { path = "../../primitives", default-features = false }

[features]
default = ["std"]
std = [
    "frame-support/std",
    "chainx-primitives/std",
]
