[package]
name = "xp-assets-registrar"
version = "2.0.0-alpha.2"
authors = ["The ChainX Authors"]
edition = "2018"

[dependencies]
impl-trait-for-tuples = "0.1.3"

# Substrate pallets
frame-support = { version = "2.0.0", default-features = false }

# ChainX primitives
chainx-primitives = { path = "../../primitives", default-features = false }

[features]
default = ["std"]
std = [
    # Substrate pallets
    "frame-support/std",
    # ChainX primitives
    "chainx-primitives/std",
]
