[package]
name = "xpallet-mining-staking-rpc-runtime-api"
version = "5.2.1"
authors = ["The ChainX Authors"]
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }

# Substrate primitives
sp-api = { git = "https://github.com/chainx-org/substrate", branch = "polkadot-v0.9.18-fix", default-features = false }
sp-std = { git = "https://github.com/chainx-org/substrate", branch = "polkadot-v0.9.18-fix", default-features = false }

# ChainX pallets
xpallet-mining-staking = { path = "../..", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    # Substrate primitives
    "sp-api/std",
    "sp-std/std",
    # ChainX pallets
    "xpallet-mining-staking/std",
]
