[package]
name = "xpallet-mining-staking-rpc-runtime-api"
version = "2.0.0-alpha.0"
authors = ["ChainX community <https://www.chainx.org>"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false }
sp-api = { version = "2.0.0-rc6", default-features = false }
sp-std = { version = "2.0.0-rc6", default-features = false }

xpallet-mining-staking = { path = "../..", default-features = false }
xpallet-support = { path = "../../../../support", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "sp-api/std",
    "sp-std/std",

    "xpallet-mining-staking/std",
    "xpallet-support/std",
]
