[package]
name = "xrml-support"
version = "0.1.0"
authors = ["ChainX community <http://www.chainx.org>"]
edition = "2018"

[dependencies]
rustc-hex = { version = "2.0", optional = true }

sp-std = { git = "https://github.com/paritytech/substrate.git", tag = "v2.0.0-rc3", default-features = false }

frame-support = { git = "https://github.com/paritytech/substrate.git", tag = "v2.0.0-rc3", default-features = false }

[features]
default = ["std"]
std = [
    "rustc-hex",

    "sp-std/std",
    "frame-support/std",
]