[package]
name = "xrml-xmining-tokens"
version = "0.4.0"
authors = ["Chainpool <http://chainx.org>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "3.2", default-features = false, features = ["derive"] }
# Substrate
substrate-primitives = { git = "https://github.com/chainpool/substrate", default-features = false }
rstd = { package = "sr-std", git = "https://github.com/chainpool/substrate", default-features = false }
primitives = { package = "sr-primitives", git = "https://github.com/chainpool/substrate", default-features = false }
support = { package = "srml-support", git = "https://github.com/chainpool/substrate", default-features = false }
system = { package = "srml-system", git = "https://github.com/chainpool/substrate", default-features = false }
timestamp = { package ="srml-timestamp", git = "https://github.com/chainpool/substrate", default-features = false }
# ChainX
xsystem = { package = "xrml-xsystem", path = "../../xsystem", default-features = false }
xsupport = { package = "xrml-xsupport", path = "../../xsupport", default-features = false }
xassets = { package = "xrml-xassets-assets", path = "../../xassets/assets", default-features = false }
xbitcoin = { package = "xrml-xbridge-bitcoin", path = "../../xbridge/bitcoin", default-features = false }
xsdot = { package = "xrml-xbridge-sdot", path = "../../xbridge/sdot", default-features = false }
xspot = { package = "xrml-xdex-spot", path = "../../xdex/spot", default-features = false }
xstaking = { package = "xrml-xmining-staking", path = "../../xmining/staking", default-features = false }

[dev-dependencies]

[features]
default = ["std"]
std = [
    "serde/std",
    "serde_derive",
    "parity-codec/std",
    # Substrate
    "substrate-primitives/std",
    "rstd/std",
    "primitives/std",
    "support/std",
    "system/std",
    "timestamp/std",
    # ChainX
    "xsystem/std",
    "xsupport/std",
    "xassets/std",
    "xbitcoin/std",
    "xspot/std",
    "xstaking/std",
]
