[package]
name = "xrml-mining-tokens"
version = "0.4.0"
authors = ["Chainpool <http://chainx.org>"]
edition = "2018"

[dependencies]
hex-literal = "0.1.0"
serde = { version = "1.0", default_features = false }
serde_derive = { version = "1.0", optional = true }
safe-mix = { version = "1.0", default_features = false}
parity-codec = { version = "3.1", default-features = false }
parity-codec-derive = { version = "3.1", default-features = false }
substrate-keyring = { git = "https://github.com/chainpool/substrate", optional = true }
substrate-primitives = { git = "https://github.com/chainpool/substrate", default_features = false }
rstd = { package = "sr-std", git = "https://github.com/chainpool/substrate", default_features = false }
runtime_io = { package = "sr-io", git = "https://github.com/chainpool/substrate", default_features = false }
primitives = { package = "sr-primitives", git = "https://github.com/chainpool/substrate", default_features = false }
runtime_support = { package = "srml-support", git = "https://github.com/chainpool/substrate", default_features = false }
system = { package = "srml-system", git = "https://github.com/chainpool/substrate", default_features = false }
balances = { package = "srml-balances", git = "https://github.com/chainpool/substrate", default_features = false }
consensus = { package = "srml-consensus", git = "https://github.com/chainpool/substrate", default_features = false }
timestamp = { package ="srml-timestamp", git = "https://github.com/chainpool/substrate", default_features = false }

xsystem = { package = "xrml-xsystem", path = "../../xsystem", default-features = false }
xaccounts = { package = "xrml-xaccounts", path = "../../xaccounts", default-features = false }
xsupport = { package = "xrml-xsupport", path = "../../xsupport", default_features = false }
xassets = { package = "xrml-xassets-assets", path = "../../xassets/assets", default_features = false }
xbitcoin = { package = "xrml-bridge-bitcoin", path = "../../xbridge/bitcoin", default-features = false }
xspot = { package = "xrml-xdex-spot", path = "../../xdex/spot", default_features = false }
xstaking = { package = "xrml-mining-staking", path = "../../xmining/staking", default_features = false }

[features]
default = ["std"]
std = [
    "serde/std",
    "serde_derive",
    "safe-mix/std",
    "substrate-keyring",
    "parity-codec/std",
    "parity-codec-derive/std",
    "substrate-primitives/std",
    "rstd/std",
    "runtime_io/std",
    "runtime_support/std",
    "primitives/std",
    "balances/std",
    "system/std",
    # xrml
    "xsystem/std",
    "xsupport/std",
    "xaccounts/std",
    "xstaking/std",
    "xassets/std",
]
