[package]
name = "xrml-xaccounts"
version = "0.4.0"
authors = ["Chainpool <http://chainx.org>"]

[dependencies]
url = "1.7.2"
hex-literal = "0.1.0"
serde = { version = "1.0", default_features = false }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "3.0", default-features = false }
parity-codec-derive = { version = "3.0", default-features = false }
substrate-primitives = { git = "https://github.com/chainpool/substrate", default_features = false }
sr-std = { git = "https://github.com/chainpool/substrate", default_features = false }
sr-io = { git = "https://github.com/chainpool/substrate", default_features = false }
sr-primitives = { git = "https://github.com/chainpool/substrate", default_features = false }
srml-support = { git = "https://github.com/chainpool/substrate", default_features = false }
srml-system = { git = "https://github.com/chainpool/substrate", default_features = false }
srml-consensus = { git = "https://github.com/chainpool/substrate", default_features = false }
srml-session = { git = "https://github.com/chainpool/substrate", default_features = false }
srml-balances = { git = "https://github.com/chainpool/substrate", default_features = false }
srml-timestamp = { git = "https://github.com/chainpool/substrate", default_features = false }
keys = { git = "https://github.com/chainx-org/bitcoin-rust", default-features = false }

# chainx runtime
xr-primitives = { path = "../../xr-primitives", default_features = false }

xrml-xassets-assets = { path = "../../xrml/xassets/assets",  default_features = false }

[features]
default = ["std"]
std=[
    "serde/std",
    "serde_derive",
    "parity-codec/std",
    "parity-codec-derive/std",
    "substrate-primitives/std",
    "sr-std/std",
    "sr-io/std",
    "sr-primitives/std",
    "srml-support/std",
    "srml-system/std",
    "srml-consensus/std",
    "srml-session/std",
    "srml-balances/std",
    "srml-timestamp/std",
    "xr-primitives/std",
    "xrml-xassets-assets/std",
]
