[package]
name = "xrml-xaccounts"
version = "1.0.0"
authors = ["Chainpool <http://chainx.org>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "3.3", default-features = false, features = ["derive"] }
# Substrate
substrate-primitives = { git = "https://github.com/chainpool/substrate", default-features = false }
rstd = { package = "sr-std", git = "https://github.com/chainpool/substrate", default-features = false }
primitives = { package = "sr-primitives", git = "https://github.com/chainpool/substrate", default-features = false }
support = { package = "srml-support", git = "https://github.com/chainpool/substrate", default-features = false }
system = { package = "srml-system", git = "https://github.com/chainpool/substrate", default-features = false }
consensus = { package = "srml-consensus", git = "https://github.com/chainpool/substrate", default-features = false }
# ChainX
xr-primitives = { path = "../../xr-primitives", default-features = false }
xsystem = { package ="xrml-xsystem", path = "../../xrml/xsystem", default-features = false }

[dev-dependencies]
# Substrate
runtime_io = { package = "sr-io", git = "https://github.com/chainpool/substrate" }
session = { package = "srml-session", git = "https://github.com/chainpool/substrate" }
timestamp = { package = "srml-timestamp", git = "https://github.com/chainpool/substrate" }
indices = { package = "srml-indices", git = "https://github.com/chainpool/substrate" }

[features]
default = ["std"]
std = [
    "serde/std",
    "serde_derive",
    "parity-codec/std",
    # Substrate
    "substrate-primitives/std",
    "rstd/std",
    "primitives/std",
    "support/std",
    "system/std",
    "consensus/std",
    # ChainX
    "xr-primitives/std",
    "xsystem/std",
]
