[package]
name = "xrml-xaccounts"
version = "0.4.0"
authors = ["Chainpool <http://chainx.org>"]
edition = "2018"

[dependencies]
hex-literal = "0.1.0"
serde = { version = "1.0", default_features = false }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "3.1", default-features = false }
parity-codec-derive = { version = "3.1", default-features = false }
rstd = { package = "sr-std", git = "https://github.com/chainpool/substrate", default_features = false }
primitives = { package = "sr-primitives", git = "https://github.com/chainpool/substrate", default_features = false }
support = { package = "srml-support", git = "https://github.com/chainpool/substrate", default_features = false }
system = { package = "srml-system", git = "https://github.com/chainpool/substrate", default_features = false }
consensus = { package = "srml-consensus", git = "https://github.com/chainpool/substrate", default_features = false }

# chainx runtime
xr-primitives = { path = "../../xr-primitives", default_features = false }

# chainx runtime module
xsystem = { package ="xrml-xsystem", path = "../../xrml/xsystem", default_features = false }
xassets = { package = "xrml-xassets-assets", path = "../../xrml/xassets/assets", default_features = false }

[dev-dependencies]
substrate-primitives = { git = "https://github.com/chainpool/substrate" }
runtime_io = { package = "sr-io", git = "https://github.com/chainpool/substrate" }
session = { package = "srml-session", git = "https://github.com/chainpool/substrate" }
timestamp = { package = "srml-timestamp", git = "https://github.com/chainpool/substrate", default_features = false }

balances = { package = "srml-balances", git = "https://github.com/chainpool/substrate" }

[features]
default = ["std"]
std=[
    "serde/std",
    "serde_derive",
    "parity-codec/std",
    "parity-codec-derive/std",
    "rstd/std",
    "primitives/std",
    "support/std",
    "system/std",
    "consensus/std",
    # chainx
    "xr-primitives/std",
    "xsystem/std",
    "xassets/std",
]
