[package]
name = "xrml-bridge-bitcoin"
version = "0.9.0"
authors = ["Chainpool <http://chainx.org>"]
edition = "2018"

[dependencies]
rustc-hex = { version = "2.0.1", optional = true }
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "3.2", default-features = false, features = ["derive"] }

rstd = { package = "sr-std", git = "https://github.com/chainpool/substrate", default-features = false }
runtime_primitives = { package = "sr-primitives", git = "https://github.com/chainpool/substrate", default-features = false }
# substrate runtime
support = { package = "srml-support", git = "https://github.com/chainpool/substrate", default-features = false }
system = { package = "srml-system", git = "https://github.com/chainpool/substrate", default-features = false }
balances = { package = "srml-balances", git = "https://github.com/chainpool/substrate", default-features = false }
timestamp = { package = "srml-timestamp", git = "https://github.com/chainpool/substrate", default-features = false }

# chainx runtime
xsupport = { package = "xrml-xsupport", path = "../../xsupport", default-features = false }
xassets = { package = "xrml-xassets-assets", path = "../../xassets/assets", default-features = false }
xrecords = { package = "xrml-xassets-records", path = "../../xassets/records", default-features = false }
xaccounts = { package = "xrml-xaccounts", path = "../../xaccounts", default-features = false }
xfee_manager = { package = "xrml-fee-manager", path = "../../xfee/manager", default-features = false }
xr-primitives = { path = "../../../xr-primitives", default_features = false }

# bitcoin
btc-primitives = { package = "primitives", git = "https://github.com/chainx-org/light-bitcoin", default-features = false }
btc-ser = { package = "serialization", git = "https://github.com/chainx-org/light-bitcoin", default-features = false }
merkle = { git = "https://github.com/chainx-org/light-bitcoin", default-features = false }
btc-crypto = { package = "crypto", git = "https://github.com/chainx-org/light-bitcoin", default-features = false }
btc-chain = { package = "chain", git = "https://github.com/chainx-org/light-bitcoin", default-features = false }
btc-keys = { package = "keys", git = "https://github.com/chainx-org/light-bitcoin", default-features = false }
btc-script = { package = "script", git = "https://github.com/chainx-org/light-bitcoin", default-features = false }

[dev-dependencies]
runtime_io = { package = "sr-io", git = "https://github.com/chainpool/substrate" }
substrate-primitives = { git = "https://github.com/chainpool/substrate" }
consensus = { package = "srml-consensus", git = "https://github.com/chainpool/substrate" }

xrml-xsystem = { path = "../../xsystem" }


[features]
default = ["std"]
std=[
    "rustc-hex",
    "serde/std",
    "serde_derive",
    "parity-codec/std",

    "rstd/std",
    "runtime_primitives/std",

    # substrate runtime
    "support/std",
    "system/std",
    "balances/std",
    "timestamp/std",

    # chainx runtime
    "xsupport/std",
    "xassets/std",
    "xrecords/std",
    "xaccounts/std",
    "xfee_manager/std",
    "xr-primitives/std",

    # bitcoin
    "btc-primitives/std",
    "btc-ser/std",
    "merkle/std",
    "btc-crypto/std",
    "btc-chain/std",
    "btc-keys/std",
    "btc-script/std",
]
