[package]
name = "xrml-bridge-bitcoin"
version = "0.9.0"
authors = ["Chainpool <http://chainx.org>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "3.2", default-features = false, features = ["derive"] }

sr-std = { git = "https://github.com/chainpool/substrate", default-features = false }
sr-io = { git = "https://github.com/chainpool/substrate", default-features = false }
sr-primitives = { git = "https://github.com/chainpool/substrate", default-features = false }
# substrate runtime
srml-support = { git = "https://github.com/chainpool/substrate", default-features = false }
srml-system = { git = "https://github.com/chainpool/substrate", default-features = false }
srml-balances = { git = "https://github.com/chainpool/substrate", default-features = false }
srml-consensus = { git = "https://github.com/chainpool/substrate", default-features = false }
srml-timestamp = { git = "https://github.com/chainpool/substrate", default-features = false }
# chainx runtime
xrml-xsupport = { path = "../../xsupport", default-features = false }
xrml-xassets-assets = { path = "../../xassets/assets", default-features = false }
xrml-xassets-records = { path = "../../xassets/records", default-features = false }
xrml-xaccounts = { path = "../../xaccounts", default-features = false }
xr-primitives = { path = "../../../xr-primitives", default_features = false }

# bitcoin-rust
chain = { git = "https://github.com/chainx-org/bitcoin-rust", default-features = false }
primitives = { git = "https://github.com/chainx-org/bitcoin-rust", default-features = false }
serialization = { git = "https://github.com/chainx-org/bitcoin-rust", default-features = false }
bitcrypto = { git = "https://github.com/chainx-org/bitcoin-rust", default-features = false }
script = { git = "https://github.com/chainx-org/bitcoin-rust", default-features = false }
keys = { git = "https://github.com/chainx-org/bitcoin-rust", default-features = false }
merkle = { git = "https://github.com/chainx-org/merkle.git", default-features = false }

[dev-dependencies]
substrate-primitives = { git = "https://github.com/chainpool/substrate" }
xrml-xsystem = { path = "../../xsystem" }
rustc-hex = { version = "2.0.1" }

[features]
default = ["std"]
std=[
    "serde/std",
    "serde_derive",
    "parity-codec/std",

    "sr-std/std",
    "sr-io/std",
    "sr-primitives/std",

    # substrate runtime
    "srml-support/std",
    "srml-system/std",
    "srml-balances/std",
    "srml-consensus/std",
    "srml-timestamp/std",

    # chainx runtime
    "xrml-xsupport/std",
    "xrml-xassets-assets/std",
    "xrml-xassets-records/std",
    "xrml-xaccounts/std",
    "xr-primitives/std",

    # bitcoin
    "chain/std",
    "primitives/std",
    "serialization/std",
    "bitcrypto/std",
    "script/std",
    "keys/std",
    "merkle/std",
]
