[package]
name = "xrml-xbridge-bitcoin"
version = "0.4.0"
authors = ["Chainpool <http://chainx.org>"]

[dependencies]
hex-literal = { version = "0.1", optional = true }
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "2.1", default-features = false }
parity-codec-derive = { version = "2.1" }

substrate-primitives = { git = "https://github.com/chainpool/substrate", default-features = false }
sr-std = { git = "https://github.com/chainpool/substrate", default-features = false }
sr-io = { git = "https://github.com/chainpool/substrate", default-features = false }
sr-primitives = { git = "https://github.com/chainpool/substrate", default-features = false }
# substrate runtime
srml-support = { git = "https://github.com/chainpool/substrate", default-features = false }
srml-system = { git = "https://github.com/chainpool/substrate", default-features = false }
srml-balances = { git = "https://github.com/chainpool/substrate", default-features = false }
srml-consensus = { git = "https://github.com/chainpool/substrate", default-features = false }
srml-timestamp = { git = "https://github.com/chainpool/substrate", default-features = false }
# chainx runtime
xrml-xsupport = { path = "../../xsupport", default-features = false }
xrml-xsystem = { path = "../../xsystem", default-features = false }
xrml-xassets-assets = { path = "../../xassets/assets", default-features = false }
xrml-xassets-records = { path = "../../xassets/records", default-features = false }

# bitcoin-rust
chain = { git = "https://github.com/chainx-org/bitcoin-rust", default-features = false }
primitives = { git = "https://github.com/chainx-org/bitcoin-rust", default-features = false }
serialization = { git = "https://github.com/chainx-org/bitcoin-rust", default-features = false }
bitcrypto = { git = "https://github.com/chainx-org/bitcoin-rust", default-features = false }
script = { git = "https://github.com/chainx-org/bitcoin-rust", default-features = false }
keys = { git = "https://github.com/chainx-org/bitcoin-rust", default-features = false }
merkle = { git = "https://github.com/chainx-org/merkle.git", default-features = false }
bit-vec =  { git = "https://github.com/chainx-org/bit-vec.git", default-features = false }
rustc-hex = { version = "2", optional = true }
base58 = { version = "0.1", optional = true }

[features]
default = ["std"]
std=[
    "hex-literal",
    "serde/std",
    "serde_derive",
    "parity-codec/std",

    "substrate-primitives/std",
    "sr-std/std",
    "sr-io/std",
    "sr-primitives/std",
    # substrate runtime
    "srml-support/std",
    "srml-system/std",
    "srml-balances/std",
    "srml-consensus/std",
    "srml-timestamp/std",
    # chainx runtime
    "xrml-xsystem/std",
    "xrml-xsupport/std",
    "xrml-xassets-assets/std",
    "xrml-xassets-records/std",
    # bitcoin
    "chain/std",
    "keys/std",
    "primitives/std",
    "serialization/std",
    "bitcrypto/std",
    "script/std",
    "merkle/std",
    "bit-vec/std",
    "rustc-hex",
    "base58",
]
