[package]
name = "cxrml-mining-tokenstaking"
version = "0.1.0"
authors = ["Chainpool <http://chainx.org>"]


[dependencies]
hex-literal = "0.1.0"
serde = { version = "1.0", default_features = false }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "2.0", default-features = false }
parity-codec-derive = { version = "2.0", default-features = false }
substrate-primitives = { git = "https://github.com/paritytech/substrate", default_features = false }
sr-std = { git = "https://github.com/paritytech/substrate", default_features = false }
sr-io = { git = "https://github.com/paritytech/substrate", default_features = false }
sr-primitives = { git = "https://github.com/paritytech/substrate", default_features = false }
srml-support = { git = "https://github.com/paritytech/substrate", default_features = false }
srml-system = { git = "https://github.com/paritytech/substrate", default_features = false }
srml-timestamp = { git = "https://github.com/paritytech/substrate", default_features = false }
srml-balances = { git = "https://github.com/paritytech/substrate", default_features = false }

# chainx runtime module
cxrml-system = { path = "../../system", default_features = false }
cxrml-support = { path = "../../support",  default_features = false }
cxrml-associations = { path = "../../associations", default_features = false }
cxrml-tokenbalances = { path = "../../tokenbalances", default_features = false }
cxrml-mining-staking = { path = "../staking", default_features = false }
cxrml-funds-financialrecords = { path = "../../funds/financialrecords", default_features = false }
cxrml-exchange-pendingorders = { path = "../../exchange/pendingorders", default_features = false }
cxrml-bridge-btc = { path = "../../bridge/btc", default_features = false }

[features]
default = ["std"]
std=[
    "serde/std",
    "serde_derive",
    "parity-codec/std",
    "parity-codec-derive/std",
    "substrate-primitives/std",
    "sr-std/std",
    "sr-io/std",
    "sr-primitives/std",
    "srml-support/std",
    "srml-system/std",
    "srml-timestamp/std",
    "srml-balances/std",
    # cxrml
    "cxrml-system/std",
    "cxrml-support/std",
    "cxrml-associations/std",
    "cxrml-tokenbalances/std",
    "cxrml-mining-staking/std",
    "cxrml-funds-financialrecords/std",
    "cxrml-exchange-pendingorders/std",
    "cxrml-bridge-btc/std",
]