[package]
name = "xpallet-gateway-bitcoin-v2"
version = "2.0.1"
authors = ["The ChainX Authors"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.6", default-features = false, features = ["derive"] }
impl-trait-for-tuples = "0.2.0"
serde = { version = "1.0.101", optional = true, features = ["derive"] }
sha2 = { version = "0.8.0", default-features = false }

# Substrate
sp-arithmetic = { version = "2.0.1", default-features = false }
sp-core = { version = "2.0.1", default-features = false }
sp-io = { version = "2.0.1", default-features = false }
sp-inherents = { version = "2.0.1", default-features = false }
sp-runtime = { version = "2.0.1", default-features = false }
sp-std = { version = "2.0.1", default-features = false }
sp-version = { version = "2.0.1", default-features = false }
frame-support = { version = "2.0.1", default-features = false }
frame-system = { version = "2.0.1", default-features = false }

# ChainX pallet
xpallet-assets = { path = "../../../assets", default-features = false }
xpallet-assets-registrar = { path = "../../../assets-registrar", default-features = false }

# light-bitcoin
light-bitcoin = { git = "https://github.com/chainx-org/light-bitcoin", branch = "master", default-features = false }

[dev-dependencies]
pallet-balances = "2.0.1"

[features]
default = ["std"]
std = [
  "codec/std",
  "serde",
  "sha2/std",
  "sp-arithmetic/std",
  "sp-core/std",
  "sp-io/std",
  "sp-inherents/std",
  "sp-runtime/std",
  "sp-std/std",
  "sp-version/std",
  "frame-support/std",
  "frame-system/std",
  "xpallet-assets/std",
  "xpallet-assets-registrar/std",
  # light-bitcoin
  "light-bitcoin/std",
]
