[package]
name = "xpallet-gateway-bitcoin-v2"
version = "2.0.1"
authors = ["The ChainX Authors"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.6", default-features = false, features = ["derive"] }
impl-trait-for-tuples = "0.2.0"
serde = { version = "1.0.101", optional = true, features = ["derive"] }

sp-core = { version = "2.0.1", default-features = false }
sp-io = { version = "2.0.1", default-features = false }
sp-inherents = { version = "2.0.1", default-features = false }
sp-runtime = { version = "2.0.1", default-features = false }
sp-std = { version = "2.0.1", default-features = false }
sp-version = { version = "2.0.1", default-features = false }
frame-support = { version = "2.0.1", default-features = false }
frame-system = { version = "2.0.1", default-features = false }


[features]
default = ["std"]
std = [
	"codec/std",
	"serde",
	"sp-core/std",
	"sp-io/std",
	"sp-inherents/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-version/std",
	"frame-support/std",
	"frame-system/std",
]
