[package]
name = "xrml-xdex-spot"
version = "1.0.0"
authors = ["Chainpool <https://www.chainx.org>"]
edition = "2018"

[dependencies]
log = "0.4"
chrono = "0.4"
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "3.3", default-features = false, features = ["derive"] }
# Substrate
substrate-primitives = { git = "https://github.com/chainpool/substrate", default-features = false }
rstd = { package = "sr-std", git = "https://github.com/chainpool/substrate", default-features = false }
runtime-io = { package = "sr-io", git = "https://github.com/chainpool/substrate", default-features = false }
primitives = { package = "sr-primitives", git = "https://github.com/chainpool/substrate", default-features = false }
support = { package = "srml-support", git = "https://github.com/chainpool/substrate", default-features = false }
system = { package = "srml-system", git = "https://github.com/chainpool/substrate", default-features = false }
timestamp = { package ="srml-timestamp", git = "https://github.com/chainpool/substrate", default-features = false }
# ChainX
xsupport = { package = "xrml-xsupport", path = "../../xsupport", default-features = false }
xassets = { package = "xrml-xassets-assets", path = "../../xassets/assets", default-features = false }

[dev-dependencies]
# Substrate
indices = { package = "srml-indices", git = "https://github.com/chainpool/substrate" }
consensus = { package = "srml-consensus", git = "https://github.com/chainpool/substrate" }
# ChainX
xsystem = { package = "xrml-xsystem", path = "../../xsystem" }
xaccounts = { package = "xrml-xaccounts", path = "../../xaccounts" }
xbitcoin = { package = "xrml-xbridge-bitcoin", path = "../../xbridge/bitcoin" }
xrecords = { package = "xrml-xassets-records", path = "../../xassets/records" }
xfee-manager = { package = "xrml-xfee-manager", path = "../../xfee/manager" }
xr-primitives = { path = "../../../xr-primitives" }

[features]
default = ["std"]
std = [
    "serde/std",
    "serde_derive",
    "parity-codec/std",
    # Substrate
    "substrate-primitives/std",
    "rstd/std",
    "runtime-io/std",
    "primitives/std",
    "support/std",
    "system/std",
    "timestamp/std",
    # ChainX
    "xsupport/std",
    "xassets/std",
]
