name: pages
on: workflow_dispatch

jobs:
  rust:
    name: doc
    runs-on: ubuntu-latest
    container:
      image: chainxorg/srtool:nightly-2020-09-30
    env:
      GHP_UPLOAD_VERSION:0.3.2
    steps:
      - name: install
        run: cargo install --version $GHP_UPLOAD_VERSION cargo-ghp-upload

    steps:
      - name: deploy
        run: cargo doc --verbose && cargo ghp-upload -vv
